### ISSUE TITLE
bug - build_definititions.yml

### ISSUE THREAD

**Issue by pachecoalbert** [damienaicheh/azure-devops-terraform-provider-tutorial-series#1]
In the docs you have 
yml_path    = "azure_pipeline.yml"
but it should be
yml_path    = "azure-pipelines.yml"
to match the repo file name.

Here is what I updated it to.

Thank you for the tutorial.  
Al

#############################################

resource "azuredevops_build_definition" "build_definitions" {
  count      = length(var.repositories)
  project_id = azuredevops_project.this.id
  name       = "${var.repositories[count.index].domain}_${var.repositories[count.index].type}_${var.repositories[count.index].application}"

  repository {
    repo_type   = "TfsGit"
    branch_name = "refs/heads/develop"
    repo_id     = azuredevops_git_repository.this[count.index].id
    yml_path    = "azure-pipelines.yml"
  }

  ci_trigger {
    use_yaml = true
  }
}

**Comment by damienaicheh** [comment]
I merged it thanks!

**Comment by mightywomble** [comment]
the codes merged, just as a point of reference, you might want to update the webpage as well :-)
Ta, great work, love this tutorial

**Comment by damienaicheh** [comment]
Finally had time to do it :)
